### PR TITLE
Update Catalan translation

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by davelab6** [comment]
Great stuff @rbuj :D

**Comment by iamutkarshtiwari** [comment]
@davelab6 Isn't @leonardcj responsible for generating all translation related PR from pootle?

**Comment by davelab6** [comment]
@iamutkarshtiwari sure, but @rbuj has contributed via github. 

Perhaps @leonardcj can take this patch and integrate it into pootle/etc and close this PR :)

**Comment by leonardcj** [comment]
This pull request can be closed without action rbuj has made the same contribution to our Pootle instance.

**Pull request closed without merging**
