### PR TITLE
Add more books around 3416 within Internet Archive

### PR DESCRIPTION
**Pull request by ortegaps**
Add around 3416 books

### CODE REVIEW

**Review by walterbender — CHANGES_REQUESTED** [review]
In general these changes look good, but they should be split into at least two pull requests. The changes to GetIABooksActivity.py are unrelated to the changes to the catalog. A detailed explanation of why these changes were made should be in the pull request message.

Regarding the changes to the catalog, you made some unexplained changes and deletions which also need to be discussed in the pull request message.

**Comment by ortegaps** [comment]
Apologies, add more books and also change the appearance of the button so that it is not very simple and also changed the size of a certain object.
But change it back by putting it as it was previously and modifying only the file get-books.cfg

**Comment by quozl** [comment]
Commit 5e1c676 only adds a blank line; what for?  I think the commit should be removed, and the commit description moved into the first commit.

Commit 9b72427 should be split into separate commits as Walter had already said.

**Comment by quozl** [comment]
Introducing the terminology;

* source; an OPDS or search query organisation,
* catalog; a subject or category subset of a source,

For example; a source definition;

```
[Feedbooks]
name = Feedbooks
query_uri = http://www.feedbooks.com/books/search.atom?query=
opds_cover = http://opds-spec.org/image
```

For example; a catalog definition within the source;

```
[Catalogs_Feedbooks]
Science Fiction = http://www.feedbooks.com/books/top.atom?category=FBFIC028000
```

Tested 9b72427.  Problems;

- [ ] the new catalogs you added are listed as within the Internet Archive, which is at `archive.org`, yet they are accessing `ebooksgratuits.com` and `openedition.org`; this is misleading and wrong; instead these new URLs should be added as catalogs within new sources of `[Ebooks Gratuits]` and `[Open Edition]`,
- [ ] when one of your new sources is selected, then a search by keyword, the Internet Archive is queried instead of the OPDS of the new source; as a result of the above.

Did you test this?  What was your test plan?  My test plan;

* open the activity,
* search Feedbooks for *prejudice*,
* search Internet Archive for *prejudice*,
* click on each catalog within a source, and search for a keyword.

**Comment by quozl** [comment]
See 97e85651c96e82467eadb4fe280183ca3885adcb in the *haiti2* branch for a method to parameterise non-OPDS sources.

**Comment by quozl** [comment]
No, don't delete Internet Archive, it works fine.  Try to find out why it doesn't work for you.  Or give me a test case or activity logs.

**Comment by quozl** [comment]
@ortegaps, this pull request apparently superseded by #12, so can you please close this one?

**Comment by ortegaps** [comment]
I try searching for something and I found it, just that you should look for
it by name or reference and I did not find a link to add a catalog

I add the Internet Archive again
Is that correct?

2016-12-22 23:30 GMT-03:00 James Cameron <notifications@github.com>:

**Comment by quozl** [comment]
@ortegaps, this pull request #10 apparently superseded by #12, so can you please close this one?

**Comment by ortegaps** [comment]
I close the #12

**Pull request closed without merging**
