### PR TITLE
remove EPUB support

### LINKED ISSUE #21: Remove EPUB
Read has lost EPUB support
https://github.com/sugarlabs/read-activity/commit/69769eed93b99a0d1cd71823349c5adb418d3dd8

So perhaps we should remove EPUB support from get-books-activity?

### PR DESCRIPTION
**Pull request by ananyaarun**
This patch removes EPUB support.
Fixes #21

### CODE REVIEW

**Comment by ananyaarun** [comment]
@quozl  @walterbender  please review ... r there any more changes to be made ?

**Comment by chimosky** [comment]
Tested. Reviewed. Thanks.

**Comment by lkundrak** [comment]
This would imply losing Feedbooks support completely, since they're deprecating PDF support (in fact it no longer works, see #25).

**Comment by quozl** [comment]
In that case the Feedbooks support should be removed at the same time.

Alternatively, add EPUB support to Read, thus removing the cause of #21.

**Comment by lkundrak** [comment]
> In that case the Feedbooks support should be removed at the same time.
> 
> Alternatively, add EPUB support to Read, thus removing the cause of #21.

Perhaps it wouldn't be too difficult to re-add it, see https://github.com/sugarlabs/read-activity/pull/29

**Comment by Aniket21mathur** [comment]
Is this pull request needed to be kept open any more?
Thanks!

**Comment by quozl** [comment]
@ananyaarun, thanks for your work, but in the end we found someone to add EPUB support back to Read activity.

**Pull request closed without merging**
